name: Deploy to Vercel

on:
  push:
    branches:
      - main # ou "master" dependendo do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy na Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN --confirm --scope=$VERCEL_SCOPE --project $VERCEL_PROJECT_ID
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE || github.repository_owner }}
